<template>
  <div class="button">
    <title-input title="button" />
    <div class="guide__wrap">
      <div class="guide-box">
        <ButtonCmp bgBtn="base" btnSize="large" btnTxt="default" />
        <ButtonCmp bgBtn="dark" btnSize="large" btnTxt="default" />
        <ButtonCmp bgBtn="disabled" disabled btnSize="large" btnTxt="default" />
      </div>
      <div class="guide-box">
        <ButtonCmp
          bgBtn="base"
          btnSize="large"
          icon
          iconPosition
          btnTxt="default-icon-right"
        />
        <ButtonCmp
          bgBtn="dark"
          btnSize="large"
          icon
          iconPosition
          btnTxt="default-icon-right"
        />
        <ButtonCmp
          bgBtn="disabled"
          disabled
          btnSize="large"
          icon
          iconPosition
          btnTxt="default-icon-right"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          bgBtn="base"
          btnSize="large"
          icon
          btnTxt="default-icon-center"
        />
        <ButtonCmp
          bgBtn="dark"
          btnSize="large"
          icon
          btnTxt="default-icon-center"
        />
        <ButtonCmp
          bgBtn="disabled"
          disabled
          btnSize="large"
          icon
          btnTxt="default-icon-center"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          bgBtn="base"
          btnSize="large"
          icon2
          iconPosition
          btnTxt="default-icon-center"
        />
        <ButtonCmp
          bgBtn="dark"
          btnSize="large"
          icon2
          iconPosition
          btnTxt="default-icon-center"
        />
        <ButtonCmp
          bgBtn="disabled"
          disabled
          btnSize="large"
          icon2
          iconPosition
          btnTxt="default-icon-left"
        />
      </div>
    </div>
    <div class="guide__wrap">
      <div class="guide-box">
        <ButtonCmp bdBtn="base" btnSize="large" btnTxt="border" />
        <ButtonCmp bdBtn="dark" btnSize="large" btnTxt="border" />
        <ButtonCmp bdBtn="disabled" disabled btnSize="large" btnTxt="border" />
      </div>
      <div class="guide-box">
        <ButtonCmp
          bdBtn="base"
          btnSize="large"
          icon
          iconPosition
          btnTxt="border-icon-right"
        />
        <ButtonCmp
          bdBtn="dark"
          btnSize="large"
          icon
          iconPosition
          btnTxt="border-icon-right"
        />
        <ButtonCmp
          bdBtn="disabled"
          disabled
          btnSize="large"
          icon
          iconPosition
          btnTxt="defauborderlt-icon-right"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          bdBtn="base"
          btnSize="large"
          icon
          btnTxt="border-icon-center"
        />
        <ButtonCmp
          bdBtn="dark"
          btnSize="large"
          icon
          btnTxt="border-icon-center"
        />
        <ButtonCmp
          bdBtn="disabled"
          disabled
          btnSize="large"
          icon
          btnTxt="border-icon-center"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          bdBtn="base"
          btnSize="large"
          icon2
          iconPosition
          btnTxt="border-icon-left"
        />
        <ButtonCmp
          bdBtn="dark"
          btnSize="large"
          icon2
          iconPosition
          btnTxt="border-icon-left"
        />
        <ButtonCmp
          bdBtn="disabled"
          disabled
          btnSize="large"
          icon2
          iconPosition
          btnTxt="border-icon-left"
        />
      </div>
    </div>
    <div class="guide__wrap">
      <div class="guide-box">
        <ButtonCmp hvBtn="base" btnSize="large" btnTxt="default" />
        <ButtonCmp hvBtn="disabled" disabled btnSize="large" btnTxt="default" />
      </div>
      <div class="guide-box">
        <ButtonCmp
          hvBtn="base"
          btnSize="large"
          icon
          iconPosition
          btnTxt="hover-icon-right"
        />
        <ButtonCmp
          hvBtn="disabled"
          disabled
          btnSize="large"
          icon
          iconPosition
          btnTxt="hover-icon-right"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          hvBtn="base"
          btnSize="large"
          icon
          btnTxt="hover-icon-center"
        />
        <ButtonCmp
          hvBtn="disabled"
          disabled
          btnSize="large"
          icon
          btnTxt="hover-icon-center"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          hvBtn="base"
          btnSize="large"
          icon2
          iconPosition
          btnTxt="hover-icon-left"
        />
        <ButtonCmp
          hvBtn="disabled"
          disabled
          btnSize="large"
          icon2
          iconPosition
          btnTxt="hover-icon-left"
        />
      </div>
    </div>
    <div class="guide__wrap">
      <div class="guide-box">
        <ButtonCmp bgBtn="base" btnSize="medium" btnTxt="default-medium" />
        <ButtonCmp bgBtn="dark" btnSize="medium" btnTxt="default-medium" />
        <ButtonCmp
          bgBtn="disabled"
          disabled
          btnSize="medium"
          btnTxt="default-medium"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          bgBtn="base"
          btnSize="medium"
          icon
          iconPosition
          btnTxt="default-medium-icon-right"
        />
        <ButtonCmp
          bgBtn="dark"
          btnSize="medium"
          icon
          iconPosition
          btnTxt="default-medium-icon-right"
        />
        <ButtonCmp
          bgBtn="disabled"
          disabled
          btnSize="medium"
          icon
          iconPosition
          btnTxt="default-medium-icon-right"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          bgBtn="base"
          btnSize="medium"
          icon
          btnTxt="default-medium-icon-center"
        />
        <ButtonCmp
          bgBtn="dark"
          btnSize="medium"
          icon
          btnTxt="default-medium-icon-center"
        />
        <ButtonCmp
          bgBtn="disabled"
          disabled
          btnSize="medium"
          icon
          btnTxt="default-medium-icon-center"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          bgBtn="base"
          btnSize="medium"
          icon2
          iconPosition
          btnTxt="default-medium-icon-center"
        />
        <ButtonCmp
          bgBtn="dark"
          btnSize="medium"
          icon2
          iconPosition
          btnTxt="default-medium-icon-center"
        />
        <ButtonCmp
          bgBtn="disabled"
          disabled
          btnSize="medium"
          icon2
          iconPosition
          btnTxt="default-medium-icon-left"
        />
      </div>
    </div>
    <div class="guide__wrap">
      <div class="guide-box">
        <ButtonCmp bdBtn="base" btnSize="medium" btnTxt="border-medium" />
        <ButtonCmp bdBtn="dark" btnSize="medium" btnTxt="border-medium" />
        <ButtonCmp
          bdBtn="disabled"
          disabled
          btnSize="medium"
          btnTxt="border-medium"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          bdBtn="base"
          btnSize="medium"
          icon
          iconPosition
          btnTxt="border-medium-icon-right"
        />
        <ButtonCmp
          bdBtn="dark"
          btnSize="medium"
          icon
          iconPosition
          btnTxt="border-medium-icon-right"
        />
        <ButtonCmp
          bdBtn="disabled"
          disabled
          btnSize="medium"
          icon
          iconPosition
          btnTxt="border-medium-icon-right"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          bdBtn="base"
          btnSize="medium"
          icon
          btnTxt="border-medium-icon-center"
        />
        <ButtonCmp
          bdBtn="dark"
          btnSize="medium"
          icon
          btnTxt="border-medium-icon-center"
        />
        <ButtonCmp
          bdBtn="disabled"
          disabled
          btnSize="medium"
          icon
          btnTxt="border-medium-icon-center"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          bdBtn="base"
          btnSize="medium"
          icon2
          iconPosition
          btnTxt="border-medium-icon-left"
        />
        <ButtonCmp
          bdBtn="dark"
          btnSize="medium"
          icon2
          iconPosition
          btnTxt="border-medium-icon-left"
        />
        <ButtonCmp
          bdBtn="disabled"
          disabled
          btnSize="medium"
          icon2
          iconPosition
          btnTxt="border-medium-icon-left"
        />
      </div>
    </div>
    <div class="guide__wrap">
      <div class="guide-box">
        <ButtonCmp hvBtn="base" btnSize="medium" btnTxt="hover-medium" />
        <ButtonCmp
          hvBtn="disabled"
          disabled
          btnSize="medium"
          btnTxt="hover-medium"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          hvBtn="base"
          btnSize="medium"
          icon
          iconPosition
          btnTxt="hover-medium-icon-right"
        />
        <ButtonCmp
          hvBtn="disabled"
          disabled
          btnSize="medium"
          icon
          iconPosition
          btnTxt="hover-medium-icon-right"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          hvBtn="base"
          btnSize="medium"
          icon
          btnTxt="hover-medium-icon-center"
        />
        <ButtonCmp
          hvBtn="disabled"
          disabled
          btnSize="medium"
          icon
          btnTxt="hover-medium-icon-center"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          hvBtn="base"
          btnSize="medium"
          icon2
          iconPosition
          btnTxt="hover-medium-icon-left"
        />
        <ButtonCmp
          hvBtn="disabled"
          disabled
          btnSize="medium"
          icon2
          iconPosition
          btnTxt="hover-medium-icon-left"
        />
      </div>
    </div>
    <div class="guide__wrap">
      <div class="guide-box">
        <ButtonCmp bgBtn="base" btnSize="small" btnTxt="default-small" />
        <ButtonCmp bgBtn="dark" btnSize="small" btnTxt="default-small" />
        <ButtonCmp
          bgBtn="disabled"
          disabled
          btnSize="small"
          btnTxt="default-small"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          bgBtn="base"
          btnSize="small"
          icon
          iconPosition
          btnTxt="default-small-icon-right"
        />
        <ButtonCmp
          bgBtn="dark"
          btnSize="small"
          icon
          iconPosition
          btnTxt="default-small-icon-right"
        />
        <ButtonCmp
          bgBtn="disabled"
          disabled
          btnSize="small"
          icon
          iconPosition
          btnTxt="default-small-icon-right"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          bgBtn="base"
          btnSize="small"
          icon
          btnTxt="default-small-icon-center"
        />
        <ButtonCmp
          bgBtn="dark"
          btnSize="small"
          icon
          btnTxt="default-small-icon-center"
        />
        <ButtonCmp
          bgBtn="disabled"
          disabled
          btnSize="small"
          icon
          btnTxt="default-small-icon-center"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          bgBtn="base"
          btnSize="small"
          icon2
          iconPosition
          btnTxt="default-small-icon-center"
        />
        <ButtonCmp
          bgBtn="dark"
          btnSize="small"
          icon2
          iconPosition
          btnTxt="default-small-icon-center"
        />
        <ButtonCmp
          bgBtn="disabled"
          disabled
          btnSize="small"
          icon2
          iconPosition
          btnTxt="default-small-icon-left"
        />
      </div>
    </div>
    <div class="guide__wrap">
      <div class="guide-box">
        <ButtonCmp bdBtn="base" btnSize="small" btnTxt="border-small" />
        <ButtonCmp bdBtn="dark" btnSize="small" btnTxt="border-small" />
        <ButtonCmp
          bdBtn="disabled"
          disabled
          btnSize="small"
          btnTxt="border-small"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          bdBtn="base"
          btnSize="small"
          icon
          iconPosition
          btnTxt="border-small-icon-right"
        />
        <ButtonCmp
          bdBtn="dark"
          btnSize="small"
          icon
          iconPosition
          btnTxt="border-small-icon-right"
        />
        <ButtonCmp
          bdBtn="disabled"
          disabled
          btnSize="small"
          icon
          iconPosition
          btnTxt="border-small-icon-right"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          bdBtn="base"
          btnSize="small"
          icon
          btnTxt="border-small-icon-center"
        />
        <ButtonCmp
          bdBtn="dark"
          btnSize="small"
          icon
          btnTxt="border-small-icon-center"
        />
        <ButtonCmp
          bdBtn="disabled"
          disabled
          btnSize="small"
          icon
          btnTxt="border-small-icon-center"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          bdBtn="base"
          btnSize="small"
          icon2
          iconPosition
          btnTxt="border-small-icon-left"
        />
        <ButtonCmp
          bdBtn="dark"
          btnSize="small"
          icon2
          iconPosition
          btnTxt="border-small-icon-left"
        />
        <ButtonCmp
          bdBtn="disabled"
          disabled
          btnSize="small"
          icon2
          iconPosition
          btnTxt="border-small-icon-left"
        />
      </div>
    </div>
    <div class="guide__wrap">
      <div class="guide-box">
        <ButtonCmp hvBtn="base" btnSize="small" btnTxt="hover-small" />
        <ButtonCmp
          hvBtn="disabled"
          disabled
          btnSize="small"
          btnTxt="hover-small"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          hvBtn="base"
          btnSize="small"
          icon
          iconPosition
          btnTxt="hover-small-icon-right"
        />
        <ButtonCmp
          hvBtn="disabled"
          disabled
          btnSize="small"
          icon
          iconPosition
          btnTxt="hover-small-icon-right"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          hvBtn="base"
          btnSize="small"
          icon
          btnTxt="hover-small-icon-center"
        />
        <ButtonCmp
          hvBtn="disabled"
          disabled
          btnSize="small"
          icon
          btnTxt="hover-small-icon-center"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          hvBtn="base"
          btnSize="small"
          icon2
          iconPosition
          btnTxt="hover-small-icon-left"
        />
        <ButtonCmp
          hvBtn="disabled"
          disabled
          btnSize="small"
          icon2
          iconPosition
          btnTxt="hover-small-icon-left"
        />
      </div>
    </div>
    <title-input title="link" />
    <div class="guide__wrap">
      <div class="guide-box">
        <ButtonCmp
          bgBtn="base"
          btnSize="large"
          btnTxt="underline-large"
          :btnType="false"
        />
        <ButtonCmp
          bgBtn="dark"
          btnSize="large"
          btnTxt="underline-large"
          :btnType="false"
        />
        <ButtonCmp
          bgBtn="disabled"
          disabled
          btnSize="large"
          btnTxt="underline-large"
          :btnType="false"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          :btnType="false"
          bgBtn="base"
          btnSize="large"
          icon
          iconPosition
          btnTxt="underline-large-icon-right"
        />
        <ButtonCmp
          :btnType="false"
          bgBtn="dark"
          btnSize="large"
          icon
          iconPosition
          btnTxt="underline-large-icon-right"
        />
        <ButtonCmp
          :btnType="false"
          bgBtn="disabled"
          disabled
          btnSize="large"
          icon
          iconPosition
          btnTxt="underline-large-icon-right"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          :btnType="false"
          bgBtn="base"
          btnSize="large"
          icon
          btnTxt="underline-large-icon-center"
        />
        <ButtonCmp
          :btnType="false"
          bgBtn="dark"
          btnSize="large"
          icon
          btnTxt="underline-large-icon-center"
        />
        <ButtonCmp
          :btnType="false"
          bgBtn="disabled"
          disabled
          btnSize="large"
          icon
          btnTxt="underline-large-icon-center"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          :btnType="false"
          bgBtn="base"
          btnSize="large"
          icon2
          btnTxt="underline-large-icon-left"
        />
        <ButtonCmp
          :btnType="false"
          bgBtn="dark"
          btnSize="large"
          icon2
          btnTxt="underline-large-icon-left"
        />
        <ButtonCmp
          :btnType="false"
          bgBtn="disabled"
          disabled
          btnSize="large"
          icon2
          btnTxt="underline-large-icon-left"
        />
      </div>
    </div>
    <div class="guide__wrap">
      <div class="guide-box">
        <ButtonCmp
          bdBtn="base"
          btnSize="large"
          btnTxt="default-large"
          :btnType="false"
        />
        <ButtonCmp
          bdBtn="dark"
          btnSize="large"
          btnTxt="default-large"
          :btnType="false"
        />
        <ButtonCmp
          bdBtn="disabled"
          disabled
          btnSize="large"
          btnTxt="default-large"
          :btnType="false"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          :btnType="false"
          bdBtn="base"
          btnSize="large"
          icon
          iconPosition
          btnTxt="default-large-icon-right"
        />
        <ButtonCmp
          :btnType="false"
          bdBtn="dark"
          btnSize="large"
          icon
          iconPosition
          btnTxt="default-large-icon-right"
        />
        <ButtonCmp
          :btnType="false"
          bdBtn="disabled"
          disabled
          btnSize="large"
          icon
          iconPosition
          btnTxt="default-large-icon-right"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          :btnType="false"
          bdBtn="base"
          btnSize="large"
          icon
          btnTxt="default-large-icon-center"
        />
        <ButtonCmp
          :btnType="false"
          bdBtn="dark"
          btnSize="large"
          icon
          btnTxt="default-large-icon-center"
        />
        <ButtonCmp
          :btnType="false"
          bdBtn="disabled"
          disabled
          btnSize="large"
          icon
          btnTxt="default-large-icon-center"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          :btnType="false"
          bdBtn="base"
          btnSize="large"
          icon2
          btnTxt="default-large-icon-left"
        />
        <ButtonCmp
          :btnType="false"
          bdBtn="dark"
          btnSize="large"
          icon2
          btnTxt="default-large-icon-left"
        />
        <ButtonCmp
          :btnType="false"
          bdBtn="disabled"
          disabled
          btnSize="large"
          icon2
          btnTxt="default-large-icon-left"
        />
      </div>
    </div>
    <div class="guide__wrap">
      <div class="guide-box">
        <ButtonCmp
          bgBtn="base"
          btnSize="small"
          btnTxt="underline-small"
          :btnType="false"
        />
        <ButtonCmp
          bgBtn="dark"
          btnSize="small"
          btnTxt="underline-small"
          :btnType="false"
        />
        <ButtonCmp
          bgBtn="disabled"
          disabled
          btnSize="small"
          btnTxt="underline-small"
          :btnType="false"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          :btnType="false"
          bgBtn="base"
          btnSize="small"
          icon
          iconPosition
          btnTxt="underline-small-icon-right"
        />
        <ButtonCmp
          :btnType="false"
          bgBtn="dark"
          btnSize="small"
          icon
          iconPosition
          btnTxt="underline-small-icon-right"
        />
        <ButtonCmp
          :btnType="false"
          bgBtn="disabled"
          disabled
          btnSize="small"
          icon
          iconPosition
          btnTxt="underline-small-icon-right"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          :btnType="false"
          bgBtn="base"
          btnSize="small"
          icon
          btnTxt="underline-small-icon-center"
        />
        <ButtonCmp
          :btnType="false"
          bgBtn="dark"
          btnSize="small"
          icon
          btnTxt="underline-small-icon-center"
        />
        <ButtonCmp
          :btnType="false"
          bgBtn="disabled"
          disabled
          btnSize="small"
          icon
          btnTxt="underline-small-icon-center"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          :btnType="false"
          bgBtn="base"
          btnSize="small"
          icon2
          btnTxt="underline-small-icon-left"
        />
        <ButtonCmp
          :btnType="false"
          bgBtn="dark"
          btnSize="small"
          icon2
          btnTxt="underline-small-icon-left"
        />
        <ButtonCmp
          :btnType="false"
          bgBtn="disabled"
          disabled
          btnSize="small"
          icon2
          btnTxt="underline-small-icon-left"
        />
      </div>
    </div>
    <div class="guide__wrap">
      <div class="guide-box">
        <ButtonCmp
          bdBtn="base"
          btnSize="small"
          btnTxt="default-small"
          :btnType="false"
        />
        <ButtonCmp
          bdBtn="dark"
          btnSize="small"
          btnTxt="default-small"
          :btnType="false"
        />
        <ButtonCmp
          bdBtn="disabled"
          disabled
          btnSize="small"
          btnTxt="default-small"
          :btnType="false"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          :btnType="false"
          bdBtn="base"
          btnSize="small"
          icon
          iconPosition
          btnTxt="default-small-icon-right"
        />
        <ButtonCmp
          :btnType="false"
          bdBtn="dark"
          btnSize="small"
          icon
          iconPosition
          btnTxt="default-small-icon-right"
        />
        <ButtonCmp
          :btnType="false"
          bdBtn="disabled"
          disabled
          btnSize="small"
          icon
          iconPosition
          btnTxt="default-small-icon-right"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          :btnType="false"
          bdBtn="base"
          btnSize="small"
          icon
          btnTxt="default-small-icon-center"
        />
        <ButtonCmp
          :btnType="false"
          bdBtn="dark"
          btnSize="small"
          icon
          btnTxt="default-small-icon-center"
        />
        <ButtonCmp
          :btnType="false"
          bdBtn="disabled"
          disabled
          btnSize="small"
          icon
          btnTxt="default-small-icon-center"
        />
      </div>
      <div class="guide-box">
        <ButtonCmp
          :btnType="false"
          bdBtn="base"
          btnSize="small"
          icon2
          btnTxt="default-small-icon-left"
        />
        <ButtonCmp
          :btnType="false"
          bdBtn="dark"
          btnSize="small"
          icon2
          btnTxt="default-small-icon-left"
        />
        <ButtonCmp
          :btnType="false"
          bdBtn="disabled"
          disabled
          btnSize="small"
          icon2
          btnTxt="default-small-icon-left"
        />
      </div>
    </div>
  </div>
</template>

<script>
// @ is an alias to /src
// import HelloWorld from '@/components/HelloWorld.vue'
import TitleInput from '@/components/fragments/TitleInput.vue'
import ButtonCmp from '@/components/fragments/ButtonCmp.vue'

export default {
  components: { TitleInput, ButtonCmp }
}
</script>
